export const integrationStatus = {
  gameVersion: '0.6.0',
  updatedAt: '28 ส.ค. 2026',
  completedTopics: 16,
  nextTopic: 'สำรวจศัตรูและผู้บุกรุก',
};

export const statusEffects = [
  { slug: 'erosion', en: 'Erosion', th: 'การกัดกร่อน', type: 'ดีบัฟ', owner: 'Desponia', summary: 'ลด WIS Save ลง 1 ต่อสแต็ก เมื่อจบการต่อสู้มีโอกาสสร้างความเสียหายไซคิกตามจำนวนสแต็ก และเมื่อถึง 5 สแต็กจะสร้างความเสียหายเนโครติกพร้อมทำให้หวาดกลัว', duration: 'เสีย 1 สแต็กทุก 1 Combat / 2 เทิร์นนอก Combat', stacks: 'สูงสุด 10' },
  { slug: 'heal-block', en: 'Heal Block', th: 'ปิดกั้นการฟื้นฟู', type: 'ดีบัฟ', owner: 'Desponia', summary: 'ไม่สามารถฟื้นฟู HP ได้ในระหว่างที่สถานะทำงาน', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'silenced', en: 'Silenced', th: 'ผนึกเวท', type: 'ดีบัฟ', owner: 'Desponia', summary: 'ไม่สามารถใช้ความสามารถที่มีแท็ก Spell ได้', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'concealment', en: 'Concealment', th: 'การอำพราง', type: 'บัฟ', owner: 'Desponia', summary: 'บังคับให้ศัตรูเสียเปรียบในการทอยโจมตีเมื่อโจมตีผู้มีสถานะนี้', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'charmed', en: 'Charmed', th: 'ถูกชักจูง', type: 'ดีบัฟ', owner: 'Desponia (ป้องกัน)', summary: 'เสียเปรียบในการทอยโจมตี และความเสียหายทุกชนิดที่สร้างลดลง 2', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'fear', en: 'Fear', th: 'หวาดกลัว', type: 'ดีบัฟ', owner: 'Desponia', summary: 'ถอยกลับไปทางทางเข้าดันเจี้ยนและเสียเปรียบในการทอยโจมตี', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'stun', en: 'Stun', th: 'มึนงง', type: 'ดีบัฟ', owner: 'Desponia / Rhea', summary: 'กระทำและเคลื่อนที่ไม่ได้ ผู้โจมตีได้เปรียบ ลด AC 2 และทำให้ STR/DEX Save เสียเปรียบ', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'bloom', en: 'Bloom', th: 'ผลิบาน', type: 'บัฟ', owner: 'Aura', summary: 'เมื่อจบการต่อสู้ ฟื้นฟู HP ตามจำนวนสแต็ก และอาจใช้สแต็กทั้งหมดเพื่อฟื้นฟูเพิ่มพร้อมเปลี่ยนเป็นเบ่งบานเต็มที่', duration: 'เสีย 1 สแต็กทุก 1 Combat / 2 เทิร์นนอก Combat', stacks: 'สูงสุด 20' },
  { slug: 'full-bloom', en: 'Full Bloom', th: 'เบ่งบานเต็มที่', type: 'บัฟ', owner: 'Aura', summary: 'ได้เปรียบในการทอยโจมตีระยะไกลและการทอยที่ใช้ CHA พร้อมเพิ่มความเสียหายเรเดียนต์ 1d8 ให้การโจมตี', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'faerie-fire', en: 'Faerie Fire', th: 'เพลิงภูต', type: 'ดีบัฟ', owner: 'Aura', summary: 'ลดค่าป้องกัน AC ของเป้าหมายลง 2', duration: '2 Combat / 4 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'photosynthesis', en: 'Photosynthesis', th: 'สังเคราะห์แสง', type: 'บัฟ', owner: 'Aura', summary: 'ถูกใช้ในการโจมตีครั้งถัดไปเพื่อเพิ่มความเสียหายเรเดียนต์ 1d8', duration: 'จนกว่าจะถูกใช้', stacks: 'แต่ละสแต็กแยกกัน' },
  { slug: 'blinded', en: 'Blinded', th: 'ตาบอด', type: 'ดีบัฟ', owner: 'Aura', summary: 'ผู้ติดสถานะเสียเปรียบในการทอยโจมตี และผู้ที่โจมตีเป้าหมายนี้จะได้เปรียบ', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'rooted', en: 'Rooted', th: 'ตรึงราก', type: 'ดีบัฟ', owner: 'Aura', summary: 'ไม่สามารถเคลื่อนที่ได้', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'regeneration', en: 'Regeneration', th: 'ฟื้นฟูต่อเนื่อง', type: 'บัฟ', owner: 'Aura', summary: 'เมื่อจบการต่อสู้ ฟื้นฟู HP 1d6 บวกตัวปรับ WIS', duration: '3 Combat / 6 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'sunbeam', en: 'Sunbeam', th: 'ลำแสงสุริยัน', type: 'ดีบัฟ', owner: 'Aura', summary: 'เมื่อจบการต่อสู้ ลบล่องหน สร้างความเสียหายเรเดียนต์ 1d8 และหาก CON Save ล้มเหลวจะทำให้ตาบอด', duration: '3 Combat / 6 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'thorn-vine', en: 'Thorn Vine', th: 'เถาวัลย์หนาม', type: 'พื้นที่', owner: 'Aura', summary: 'ศัตรูที่เข้าพื้นที่ได้รับความเสียหายเจาะแทง 2d6 และหาก DEX Save ล้มเหลวจะถูกตรึงราก', duration: '3 Combat / 6 เทิร์นนอก Combat', stacks: 'เอฟเฟกต์พื้นที่' },
  { slug: 'garden-defense', en: 'Garden Defense', th: 'สวนพิทักษ์', type: 'พื้นที่', owner: 'Aura', summary: 'เมื่อเริ่มการต่อสู้ สร้างความเสียหายเจาะแทง 3d6 แก่ศัตรูในพื้นที่และมอบผลิบานให้ฝ่ายเรา', duration: '4 Combat / 8 เทิร์นนอก Combat', stacks: 'เอฟเฟกต์พื้นที่' },
  { slug: 'natures-cycle', en: "Nature's Cycle", th: 'วัฏจักรธรรมชาติ', type: 'บัฟ', owner: 'Aura', summary: 'เมื่อถูกโจมตี จะได้รับผลิบานและสร้างความเสียหายเรเดียนต์ 2d8 แก่ศัตรูทั้งหมด', duration: '3 Combat / 6 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'valor', en: 'Valor', th: 'ความกล้าหาญ', type: 'บัฟ', owner: 'Rhea', summary: 'แนวหน้าได้รับ HP ชั่วคราว 1d4 ต่อสแต็กเมื่อเริ่มการต่อสู้ และใช้สแต็กเมื่อโจมตีโดนเพื่อเพิ่มความเสียหายสายฟ้า 1d8', duration: 'เสีย 1 สแต็กทุก 1 Combat / 2 เทิร์นนอก Combat', stacks: 'สูงสุด 20' },
  { slug: 'prone', en: 'Prone', th: 'ล้มลง', type: 'ดีบัฟ', owner: 'Rhea', summary: 'เสียเปรียบในการโจมตี ผู้โจมตีประชิดได้เปรียบ แต่ผู้โจมตีระยะไกลเสียเปรียบ', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'overload', en: 'Overload', th: 'ประจุเกินขีด', type: 'ดีบัฟ', owner: 'Rhea', summary: 'เมื่อจบการต่อสู้ ได้รับความเสียหายสายฟ้า 1d6', duration: '3 Combat / 6 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'lightning-shield', en: 'Lightning Shield', th: 'โล่สายฟ้า', type: 'บัฟ', owner: 'Rhea', summary: 'เมื่อถูกโจมตี สะท้อนความเสียหายสายฟ้า 1d8 กลับไปยังผู้โจมตี', duration: '2 Combat / 4 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'lightning-enchant', en: 'Lightning Enchant', th: 'เสริมพลังสายฟ้า', type: 'บัฟ', owner: 'Rhea', summary: 'การโจมตีสร้างความเสียหายสายฟ้าเพิ่ม 1d8', duration: '2 Combat / 4 เทิร์นนอก Combat', stacks: 'แต่ละสแต็กแยกกัน' },
  { slug: 'death-lightning', en: 'Death Lightning', th: 'อัสนีมรณะ', type: 'พื้นที่', owner: 'Rhea', summary: 'เมื่อต้นเทิร์น ผ่าสายฟ้าใส่ตำแหน่งสุ่ม 4 จุดที่ไม่มีฝ่ายเรา และสร้างความเสียหายสายฟ้า 3d10', duration: '3 เทิร์น', stacks: 'เอฟเฟกต์พื้นที่' },
  { slug: 'attack-disadvantage', en: 'Attack Disadvantage', th: 'เสียเปรียบในการโจมตี', type: 'ดีบัฟ', owner: 'Wendigo', summary: 'เสียเปรียบในการทอยโจมตี (Attack Roll)', duration: '2 Combat / 4 เทิร์นนอก Combat', stacks: 'แต่ละสแต็กแยกกัน' },
  { slug: 'ac-bonus', en: 'AC Bonus', th: 'โบนัส AC', type: 'บัฟ', owner: 'Wendigo', summary: 'เพิ่มค่าป้องกัน (AC) 2', duration: '2 Combat / 4 เทิร์นนอก Combat', stacks: 'แต่ละสแต็กแยกกัน' },
  { slug: 'physical-damage-resistance', en: 'Physical Damage Resistance', th: 'ต้านทานความเสียหายกายภาพ', type: 'บัฟ', owner: 'Wendigo', summary: 'ได้รับความต้านทานต่อ Bludgeoning, Piercing และ Slashing', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่ระบุ' },
  { slug: 'restrained', en: 'Restrained', th: 'ถูกพันธนาการ', type: 'ดีบัฟ', owner: 'Arachne', summary: 'เคลื่อนที่ไม่ได้ เสียเปรียบใน Attack Roll และ DEX Save ขณะที่ผู้โจมตีได้เปรียบ', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'poisoned', en: 'Poisoned', th: 'ติดพิษ', type: 'ดีบัฟ', owner: 'Arachne (ป้องกัน)', summary: 'เมื่อจบ Combat รับความเสียหายพิษ 1d4 และเสียเปรียบใน Attack Roll', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'แต่ละสแต็กแยกกัน' },
  { slug: 'web', en: 'Web', th: 'ใยแมงมุม', type: 'ดีบัฟ', owner: 'Arachne', summary: 'ลด DEX Save 1 ต่อสแต็ก เมื่อครบ 3 สแต็กจะกลายเป็นถูกพันธนาการ (Restrained)', duration: 'ไม่ระบุ', stacks: 'สูงสุด 3' },
  { slug: 'transcendent-link', en: 'Transcendent Link', th: 'สายสัมพันธ์เหนือโลก', type: 'ดีบัฟ', owner: 'Transcendent', summary: 'ความเสียหายไซคิกที่ได้รับเพิ่มตาม CHA Modifier ของผู้ร่าย', duration: 'ไม่ระบุ', stacks: 'ไม่ระบุ' },
  { slug: 'psychic-vulnerability', en: 'Psychic Vulnerability', th: 'แพ้ทางความเสียหายไซคิก', type: 'ดีบัฟ', owner: 'Transcendent', summary: 'ได้รับความเสียหาย Psychic แรงขึ้นตามระบบ Vulnerability', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
  { slug: 'confusion', en: 'Confusion', th: 'สับสน', type: 'ดีบัฟ', owner: 'Transcendent', summary: 'เป้าหมายของการกระทำจะถูกเปลี่ยนแบบสุ่ม', duration: '1 Combat / 2 เทิร์นนอก Combat', stacks: 'ไม่สะสม' },
] as const;

export const monsters = [
  ['Ratatoskr',1,'Beast','DEX','Physical',true], ['Selkie',1,'Beast','WIS','Psychic',true],
  ['Lesser Water Elemental',1,'Elemental','INT','Cold',true], ['Lesser Fire Elemental',1,'Elemental','STR','Fire',true],
  ['Lesser Air Elemental',1,'Elemental','DEX','Piercing',true], ['Slime',1,'Elemental','CON','Nature',true],
  ['Zombie',1,'Beast','CON','Bludgeoning',true], ['Skeleton',1,'Undead','DEX','Slashing',true], ['Skeleton Mage',1,'Undead','INT','Fire',true],
  ['Harpy',2,'Beast','DEX','Piercing',true], ['Tiger',2,'Beast','STR','Slashing',true],
  ['Dream Elemental',2,'Elemental','WIS','Psychic',true], ['Nymph',2,'Elemental','CHA','Psychic',true],
  ['Sprout Soldier',2,'Elemental','STR','Slashing',true], ['Ghoul',2,'Undead','DEX','Slashing',true],
  ['Death Soldier',2,'Undead','STR','None',true], ['Skeletal Steed',2,'Undead','STR','Piercing',true], ['Vampire Spawn',2,'Undead','CHA','Psychic',true],
  ['Wendigo',3,'Beast','STR','Physical',true], ['Lamia',3,'Undead','DEX','Slashing',true],
  ['Kelpie',3,'Elemental','STR','Piercing',true], ['Salamander',3,'Elemental','STR','Piercing / Fire',true],
  ['Sylph',3,'Elemental','DEX','Slashing',true], ['Ghast',3,'Undead','DEX','Slashing',true],
  ['Marionette',3,'Undead','DEX','Slashing',true], ['Banshee',3,'Undead','CHA','Psychic',true],
  ['Minotaur',4,'รอตรวจ','—','—',false], ['Griffon',4,'รอตรวจ','—','—',false], ['Manticore',4,'รอตรวจ','—','—',false],
  ['Unicorn',4,'รอตรวจ','—','—',false], ['Grief Elemental',4,'รอตรวจ','—','—',false], ['Nightmare',4,'Elemental','WIS','Psychic',true],
  ['Sprout Knight',4,'รอตรวจ','—','—',false], ['Nosferatu',4,'Undead','DEX','Piercing',true],
  ['Death Priest',4,'รอตรวจ','—','—',false], ['Death Ranger',4,'รอตรวจ','—','—',false],
  ['Sphinx',5,'Beast','INT','Bludgeoning',true], ['Basilisk',5,'Beast','WIS','Nature',true], ['Cockatrice',5,'Beast','CHA','Force',true],
  ['Water Elemental',5,'Elemental','CHA','Force',true], ['Air Elemental',5,'รอตรวจ','—','—',false], ['Fire Elemental',5,'รอตรวจ','—','—',false],
  ['Skeleton Lord',5,'รอตรวจ','—','—',false], ['Vampire',5,'รอตรวจ','—','—',false], ['Lich',5,'รอตรวจ','—','—',false],
  ['Pegasus',6,'Beast','DEX','Piercing / Radiant',true], ['Gorgon',6,'รอตรวจ','—','—',false], ['Ugallu',6,'Beast','STR','Bludgeoning',true],
  ['Mind Elemental',6,'Elemental','WIS','Psychic',true], ['Arachne',6,'Elemental','STR','Piercing',true], ['Phoenix',6,'รอตรวจ','—','—',false],
  ['Vampire Lord',6,'รอตรวจ','—','—',false], ['Night Crawler',6,'รอตรวจ','—','—',false], ['Death Knight',6,'รอตรวจ','—','—',false],
  ['Sandworm',7,'Beast','WIS','Poison',true], ['Hydra',7,'Beast','STR','Slashing',true], ['Tethys',7,'Beast','CHA','Cold',true],
  ['Fire Lord',7,'Elemental','INT','Bludgeoning / Fire',true], ['Air Lord',7,'Elemental','DEX','Piercing',true],
  ['Water Lord',7,'Elemental','INT','Cold',true], ['Titania',7,'Elemental','CHA','Radiant',true],
  ['Body Reaper',7,'Undead','STR','Bludgeoning',true], ['Soul Reaper',7,'Undead','INT','Necrotic',true], ['Abomination',7,'Undead','STR','Slashing',true],
  ['Fenrir',8,'Beast','STR','Slashing',true], ['Sleipnir',8,'Beast','STR','Piercing',true], ['Kirin',8,'Elemental','WIS','Lightning',true],
  ['Ethereal',8,'Elemental','CHA','Radiant',true], ['Lich Queen',8,'Elemental','INT','Necrotic',true], ['Nightwalker',8,'Undead','DEX','Slashing',true],
  ['Behemoth',9,'Beast','STR','Bludgeoning',true], ['Nemea',9,'Beast','INT','Force',true], ['Emmelia',9,'Elemental','WIS','Lightning',true],
  ['Transcendent',9,'Elemental','CHA','Psychic',true], ['Grim Reaper',9,'Undead','DEX','Slashing / Necrotic',true], ['Physis',9,'Undead','CHA','Necrotic',true],
] as const;

const monsterImageFileOverrides: Record<string, string> = {
  'Lesser Air Elemental': 'Lesser Air Elemental',
  'Lesser Fire Elemental': 'Lesser Fire Elemental',
  'Lesser Water Elemental': 'Lesser Water Elemental',
  'Skeleton Mage': 'skeleton_Mage',
  'Vampire Lord': 'vampire_Llord',
  Behemoth: 'Behemoth', Emmelia: 'Emmelia', Nemea: 'Nemea', Transcendent: 'Transcendent',
};

export function monsterImagePath(name: string, tier: number) {
  const fileName = monsterImageFileOverrides[name] ?? name.toLowerCase().replaceAll(' ', '_');
  return `/images/monsters/Tier ${tier}/${fileName}.png`;
}

export const prototypeMonsters = [
  {
    slug: 'wendigo', name: 'Wendigo', tier: 3, type: 'Beast', dominance: 3, roleTh: 'แนวหน้าสายรับดาเมจ', tone: 'ice',
    keyStat: 'STR', attackTypes: ['Physical'], stats: { STR: 15, DEX: 10, CON: 14, INT: 5, WIS: 10, CHA: 4, HP: 44, AC: 8, Initiative: 0 },
    immunity: ['Cold'], resistance: ['—'], vulnerability: ['—'],
    summaryTh: 'แนวหน้าที่รับการโจมตีแทนพวกพ้อง ลดความเสียหาย และทำให้ศัตรูมึนงง โดยฟื้น HP เมื่อซ้ำเป้าหมายที่เหลือเลือดไม่เกินครึ่ง',
    skills: [
      { slot: 'A', en: 'Heavy Strike', th: 'โจมตีหนัก', kind: 'การโจมตีพื้นฐาน', description: 'ฟาดศัตรูและทำให้เสียเปรียบในการโจมตี', damage: '2d4 + STR Physical', checks: 'STR Attack Roll · CON Save DC 12 + STR', statuses: ['attack-disadvantage'] },
      { slot: 'B', en: 'Insatiable Hunger', th: 'ความหิวไม่รู้จบ', kind: 'คุณลักษณะติดตัว', description: 'ป้องกัน Cold และทุกครั้งที่โจมตีโดนศัตรูที่เหลือ HP ครึ่งหนึ่งหรือน้อยกว่า จะฟื้น HP ตนเอง', damage: 'ฟื้น 1d6 + CON HP', checks: 'ทำงานเมื่อโจมตีโดน', statuses: [] },
      { slot: 'M', en: 'Ruthless Strike', th: 'โจมตีไร้ปรานี', kind: 'ชิ้นส่วนหลัก', description: 'โจมตีกายภาพอย่างรุนแรงและทำให้เป้าหมายมึนงง', damage: '3d8 + STR Physical', checks: 'STR Attack Roll · CON Save DC 12 + STR', statuses: ['stun'] },
      { slot: 'S1', en: 'Glacial Guardian', th: 'ผู้พิทักษ์ธารน้ำแข็ง', kind: 'ชิ้นส่วนเสริม 1', description: 'เมื่อพันธมิตรถูกเล็ง ใช้ Reaction รับการโจมตีแทน ลดความเสียหาย และรับโบนัส AC', damage: 'ลดความเสียหาย 2d8', checks: 'Reaction · CON +1', statuses: ['ac-bonus'] },
      { slot: 'S2', en: 'Thick Hide', th: 'หนังหนา', kind: 'ชิ้นส่วนเสริม 2', description: 'เพิ่ม HP สูงสุด 15 และเมื่อถูกโจมตีจะใช้ Reaction เพื่อรับความต้านทานต่อความเสียหายกายภาพ', damage: 'HP สูงสุด +15', checks: 'Reaction', statuses: ['physical-damage-resistance'] },
    ], sourceUpdated: '18 ส.ค. 2026',
  },
  {
    slug: 'arachne', name: 'Arachne', tier: 6, type: 'Elemental', dominance: 9, roleTh: 'แนวหน้าควบคุม', tone: 'web',
    keyStat: 'STR', attackTypes: ['Piercing'], stats: { STR: 18, DEX: 14, CON: 17, INT: 11, WIS: 11, CHA: 9, HP: 88, AC: 8, Initiative: 0 },
    immunity: ['Restrained', 'Poisoned'], resistance: ['—'], vulnerability: ['—'],
    summaryTh: 'ตัวควบคุมแนวหน้าที่สะสมใยเพื่อลด DEX Save และพันธนาการศัตรู จากนั้นจึงซ้ำด้วยการโจมตีที่คริติคอลอัตโนมัติต่อเป้าหมายที่ถูกพันธนาการ',
    skills: [
      { slot: 'A', en: 'Basic Thrust', th: 'แทงพื้นฐาน', kind: 'การโจมตีพื้นฐาน', description: 'แทงจุดอ่อนของศัตรูด้วยความเสียหายเจาะแทง', damage: '2d10 + STR Piercing', checks: 'STR Attack Roll · Critical Hit 19+', statuses: [] },
      { slot: 'B', en: 'Web Spinning', th: 'ชักใย', kind: 'คุณลักษณะติดตัว', description: 'ป้องกัน Restrained และ Poisoned เมื่อโจมตีโดนจะสร้างดาเมจกระแทกเพิ่มตามสแต็กใยของเป้าหมาย และเพิ่มใย 1 สแต็ก', damage: '+6 Bludgeoning ต่อ Web 1 สแต็ก', checks: 'ทำงานเมื่อโจมตีโดน', statuses: ['web', 'restrained', 'poisoned'] },
      { slot: 'M', en: 'Titan Stomp', th: 'กระทืบยักษ์', kind: 'ชิ้นส่วนหลัก', description: 'กระทืบเป้าหมายให้ล้ม และการโจมตีนี้จะติดคริติคอลเสมอหากเป้าหมายถูกพันธนาการ', damage: '4d12 + STR Bludgeoning', checks: 'STR · Melee', statuses: ['prone', 'restrained'] },
      { slot: 'S1', en: 'Steel Carapace', th: 'กระดองเหล็ก', kind: 'ชิ้นส่วนเสริม 1', description: 'ได้รับความต้านทานต่อ Piercing และป้องกันการโจมตีแบบ Critical Hit', damage: 'ป้องกันเชิงรับ', checks: 'ทำงานตลอดเวลา', statuses: [] },
      { slot: 'S2', en: 'Web Dome', th: 'โดมใยแมงมุม', kind: 'ชิ้นส่วนเสริม 2', description: 'เมื่อศัตรูใช้เวทพื้นที่ ใช้ Reaction เปลี่ยนเป้าหมายมาที่ตนเองและลดความเสียหายที่ได้รับ', damage: 'ลด 5d8 + CON (5–40)', checks: 'Reaction · ตอบโต้เวทพื้นที่', statuses: [] },
    ], sourceUpdated: '14 ก.ค. 2026',
  },
  {
    slug: 'transcendent', name: 'Transcendent', tier: 9, type: 'Elemental', dominance: 32, roleTh: 'แนวหลังโจมตีไซคิก', tone: 'mind',
    keyStat: 'CHA', attackTypes: ['Psychic'], stats: { STR: 6, DEX: 16, CON: 20, INT: 34, WIS: 38, CHA: 40, HP: 160, AC: 8, Initiative: 0 },
    immunity: ['Charmed', 'Psychic'], resistance: ['—'], vulnerability: ['—'],
    summaryTh: 'ตัวทำดาเมจไซคิกระดับสูง วาง Transcendent Link เพื่อขยายดาเมจต่อเนื่อง โจมตีเป้าหมายที่ถูกเชื่อมโยงได้ทั้งสนาม และรบกวนแนวหลังด้วยความสับสน',
    skills: [
      { slot: 'A', en: 'Mind Pressure', th: 'แรงกดดันทางจิต', kind: 'การโจมตีพื้นฐาน', description: 'กดดันจิตใจของเป้าหมายด้วยความเสียหายไซคิก', damage: '5d6 + CHA Psychic', checks: 'WIS Save DC 12 + CHA · Spell · Ranged', statuses: [] },
      { slot: 'B', en: 'Mind of the World', th: 'จิตแห่งโลก', kind: 'คุณลักษณะติดตัว', description: 'ป้องกัน Psychic และ Charmed ความเสียหายไซคิกของตนเองมองข้ามความต้านทานและภูมิคุ้มกัน ศัตรูที่ได้รับดาเมจไซคิกและ Save ล้มเหลวจะติดสายสัมพันธ์เหนือโลก', damage: 'ขยาย Psychic Damage', checks: 'ทำงานกับศัตรูทั้งสนาม', statuses: ['transcendent-link', 'charmed'] },
      { slot: 'M', en: 'Staff of Transcendence', th: 'คทาแห่งการก้าวข้าม', kind: 'ชิ้นส่วนหลัก', description: 'โจมตีเป้าหมายหลักและสร้างความเสียหายไซคิกเพิ่มแก่ศัตรูทุกตัวที่มีสายสัมพันธ์เหนือโลก', damage: '6d10 + CHA และ 3d8 + CHA Psychic', checks: 'CHA Attack Roll · Spell · Ranged', statuses: ['transcendent-link'] },
      { slot: 'S1', en: 'Insight into All Minds', th: 'หยั่งรู้ทุกจิต', kind: 'ชิ้นส่วนเสริม 1', description: 'เมื่อถูกโจมตี ใช้ Reaction กดดันจิตของศัตรูแนวหลัง หาก WIS Save ล้มเหลวจะใช้ Main Action ที่ยังเหลือของเป้าหมายไป 1 ครั้ง', damage: '6d12 + CHA Psychic', checks: 'Reaction · WIS Save · Back row', statuses: [] },
      { slot: 'S2', en: 'Branch of the World Tree', th: 'กิ่งแห่งต้นไม้โลก', kind: 'ชิ้นส่วนเสริม 2', description: 'เมื่อเริ่มปะทะ ทำให้ศัตรูแนวหลังแพ้ทางความเสียหายไซคิกและติดสับสน', damage: 'เอฟเฟกต์พื้นที่แนวหลัง', checks: 'INT Save + CHA · ทำงานตอนเริ่มปะทะ', statuses: ['psychic-vulnerability', 'confusion'] },
    ], sourceUpdated: '12 ส.ค. 2026',
  },
] as const;

export const darkLords = [
  {
    slug: 'desponia', name: 'Desponia', tagline: 'เจ้าแห่งความตาย ผู้ลากศัตรูลงสู่ห้วงลึก',
    unlock: 'ปลดล็อกตั้งแต่เริ่มเกม', core: 'การกัดกร่อน (Erosion)', keyStat: 'WIS', damage: ['Necrotic', 'Psychic'],
    stats: { STR: 12, DEX: 10, CON: 16, INT: 14, WIS: 18, CHA: 16, HP: 110, AC: 10, Initiative: 0 },
    immunity: 'ถูกชักจูง (Charmed)', theme: 'สะสมการกัดกร่อน (Erosion) เพื่อลด WIS Save และต่อยอดเป็นความเสียหายไซคิก/เนโครติกกับสถานะหวาดกลัว',
    playstyle: {
      archetype: 'ทีมดีบัฟสะสม แล้วระเบิดดาเมจ', difficulty: 'ปานกลาง', position: 'แนวหลัง', statFocus: 'WIS เป็นหลัก · INT / CHA / CON ตามของที่ได้',
      oneLine: 'ยื้อเวลาให้ Erosion สะสม ลด WIS Save ของศัตรู แล้วปิดการต่อสู้ด้วย Psychic/Necrotic Damage หรือคุมหมู่',
      coreLoop: ['เปิดไฟต์และกระจาย Erosion', 'ใช้แนวหน้าถ่วงเวลาให้สแต็กสูงขึ้น', 'เพิ่มสแต็กเป็นสองเท่าหรือทำให้เต็ม', 'ระเบิดดาเมจและคุมศัตรูด้วย Fear / Stun'],
      team: [
        ['แนวหน้ารับดาเมจ', '1–2 ตัว', 'ต้องอยู่ได้นานเพื่อให้ Erosion มีเวลาสะสม เลือกตัวที่มี Redirect, ลดดาเมจ, ฟื้น HP หรือคุมศัตรู'],
        ['ตัวคุมจังหวะ', '1 ตัว', 'Stun, Restrained, Fear หรือ Attack Disadvantage ช่วยลดแรงกดดันและเปิดเวลาให้ดีบัฟทำงาน'],
        ['ตัวทำดาเมจหลัก', '2–3 ตัว', 'มองหาตัวที่ใช้ WIS หรือโจมตี Psychic/Necrotic แต่ให้เลือกความแรงจริงและ Part ที่สมบูรณ์ก่อนการจับคู่สีดาเมจ'],
        ['ห้องก่อนห้องจอมมาร', '1 จุด', 'ใช้ Hunting Ground หรือจุดคุมฝูงชนเพื่อไม่ให้ศัตรูจำนวนมากทะลักเข้าห้องพร้อมกัน'],
      ],
      goodFits: ['มอนสเตอร์ WIS: Selkie, Dream Elemental, Nightmare, Basilisk, Mind Elemental, Sandworm, Kirin, Emmelia', 'ตัวอย่างแนวรับที่มีข้อมูลแล้ว: Wendigo', 'สถานะที่ช่วยทีม: Stun, Restrained, Fear, Attack Disadvantage'],
      recommendedMonsters: [['Mind Elemental', 'WIS · Psychic', 'ตัวทำดาเมจไซคิกที่เดินตามแผนลด WIS Save'], ['Nightmare', 'WIS · Psychic', 'เสริมดาเมจไซคิกและแรงกดดันจาก Fear'], ['Dream Elemental', 'WIS · Psychic', 'ตัวเลือกช่วงต้นที่ใช้ Stat และ Damage ตรงแกน'], ['Selkie', 'WIS · Psychic', 'มอนสเตอร์ Tier 1 สำหรับเริ่มทีม WIS'], ['Sandworm', 'WIS · Poison', 'เพิ่มดาเมจอีกชนิดเพื่อไม่พึ่ง Psychic อย่างเดียว'], ['Wendigo', 'STR · แนวหน้า', 'รับการโจมตีแทนทีมและซื้อเวลาสะสม Erosion']],
      authorityPlan: [['ช่วงตั้งทีม', 'Bond of Agony / Abyssal Fog', 'ประคองกลุ่มที่ HP ต่ำและซื้อเวลาให้ Erosion สะสม'], ['ช่วงกลาง Run', 'Domain Intrusion', 'เพิ่ม Erosion เป็นสองเท่าและต่อยอด Fear'], ['ตัวปิดไฟต์', 'Black Sun → Psychic Breakdown', 'ทำ Erosion ให้เต็มก่อนเปลี่ยนสแต็กเป็นดาเมจและ Stun หมู่']],
      phases: [['ต้น Run', 'หาแนวหน้าที่ไว้ใจได้ก่อน แล้วเลือกตัวใช้ WIS หรือมีสกิลคุมจังหวะ ไม่ต้องบังคับเล่น Undead ล้วน'], ['กลาง Run', 'เพิ่มความสม่ำเสมอของการกระจาย Erosion และป้องกันแนวหลัง พร้อมคุม Dominance ไม่ให้เกิน'], ['ท้าย Run', 'เตรียมดาเมจมากกว่าหนึ่งชนิด เผื่อบอสต้าน Psychic/Necrotic และเก็บ Authority ปิดไฟต์ไว้รับคลื่นอันตราย']],
      pitfalls: ['เร่งดาเมจเร็วเกินไปจน Erosion ยังไม่พอ', 'วาง Desponia ไว้แนวหน้า', 'เลือกมอนสเตอร์ตามเผ่าแทนหน้าที่และ Part', 'พึ่ง Psychic/Necrotic ชนิดเดียวโดยไม่ดูภูมิต้านทานบอส', 'Touch of the Dead มีเงื่อนไข ต้องมีศัตรูที่เคยสังหารฝ่ายเราจึงจะคุ้ม'],
      confidence: 'แกน Erosion และ Authority อ้างอิง Wiki; โครงทีมและลำดับใช้สกิลเป็นคำแนะนำเชิงวิเคราะห์ร่วมกับประสบการณ์ชุมชน',
    },
    skills: [
      ['A', 'Chill Touch', 'สัมผัสเย็นเยียบ', 'การโจมตีพื้นฐาน', 'สร้างความเสียหายเนโครติกและทำให้เป้าหมายติดปิดกั้นการฟื้นฟู (Heal Block) ชั่วคราว'],
      ['B', "Sovereign's Intimidation", 'แรงข่มขู่แห่งผู้ครอง', 'คุณลักษณะติดตัว', 'เมื่อเริ่มการต่อสู้ มีโอกาสเพิ่มการกัดกร่อน (Erosion) แก่ศัตรูทั้งหมด'],
      ['M', 'Scepter of the Abyss', 'คทาแห่งห้วงลึก', 'ชิ้นส่วนหลัก', 'มีโอกาสเพิ่มการกัดกร่อน (Erosion) และสร้างความเสียหายไซคิกเพิ่มตามจำนวนสแต็กของเป้าหมาย'],
      ['S1', 'Evil Eye of Insight', 'ดวงตาปีศาจหยั่งรู้', 'ชิ้นส่วนเสริม', 'เมื่อศัตรูโจมตีพลาด จะตอบโต้ด้วยการกัดกร่อน (Erosion) และความเสียหายไซคิกตามจำนวนสแต็ก'],
      ['S2', 'Shadow Veil', 'ม่านเงา', 'ชิ้นส่วนเสริม', 'ต้านทานการโจมตีระยะไกล และเมื่อถูกโจมตีจะมีโอกาสเพิ่มการกัดกร่อน (Erosion) แก่ศัตรูทั้งหมด'],
    ],
    authorities: [
      ['Nightmare Injection', 'ฝังฝันร้าย', 'โจมตีกลุ่มศัตรูที่ใกล้ที่สุดด้วยความเสียหายเนโครติกและเพิ่มการกัดกร่อน (Erosion) 2 สแต็ก'],
      ['Forced Execution', 'บังคับประหาร', 'สร้างความเสียหายไซคิก และเพิ่มความเสียหายตามจำนวนการกัดกร่อน (Erosion) ของเป้าหมาย'],
      ['Hand of the Void', 'หัตถ์แห่งความว่างเปล่า', 'ทำให้กลุ่มศัตรูที่กำลังปะทะติดผนึกเวท (Silenced) และใช้ Spell ไม่ได้'],
      ['Abyssal Fog', 'หมอกแห่งห้วงลึก', 'มอบการอำพราง (Concealment) ให้กลุ่มฝ่ายเราที่มีสัดส่วน HP ต่ำที่สุด'],
      ['Bond of Agony', 'พันธะแห่งความทรมาน', 'มอบ HP ชั่วคราวให้กลุ่มฝ่ายเราที่มีสัดส่วน HP ต่ำที่สุด'],
      ['Domain Intrusion', 'รุกล้ำอาณาเขต', 'เพิ่มการกัดกร่อน (Erosion) ของศัตรูทุกตัวเป็นสองเท่า และมีโอกาสทำให้หวาดกลัว (Fear)'],
      ['Touch of the Dead', 'สัมผัสแห่งความตาย', 'โจมตีศัตรูที่เคยสังหารฝ่ายเราด้วยความเสียหายเนโครติกและเพิ่มการกัดกร่อน (Erosion) 5 สแต็ก'],
      ['Black Sun', 'สุริยะทมิฬ', 'โจมตีศัตรูทั้งหมดในสนามด้วยความเสียหายเนโครติกรุนแรงและทำให้การกัดกร่อน (Erosion) เต็ม'],
      ['Psychic Breakdown', 'จิตแตกสลาย', 'โจมตีศัตรูทั้งหมดด้วยความเสียหายไซคิกและทำให้มึนงง (Stun) ตามจำนวน Erosion สูงสุด 3 เทิร์น'],
    ],
    relics: ['Ominous Fog', 'Skull of Amplification', 'Echo of Agony', 'Plague Bomb'],
    sourceUpdated: '18 ส.ค. 2026', tone: 'purple',
  },
  {
    slug: 'aura', name: 'Aura', tagline: 'ผู้พิทักษ์แห่งวิญญาณ ผู้หล่อเลี้ยงชีวิต',
    unlock: 'ปลดล็อกตั้งแต่เริ่มเกม', core: 'ผลิบาน / เบ่งบานเต็มที่', keyStat: 'DEX', damage: ['Piercing', 'Radiant'],
    stats: { STR: 10, DEX: 18, CON: 14, INT: 10, WIS: 16, CHA: 14, HP: 80, AC: 10, Initiative: 5 },
    immunity: 'ไม่มีตาม Wiki', theme: 'สร้างผลิบาน (Bloom) เพื่อฟื้นฟู ก่อนเปลี่ยนเป็นเบ่งบานเต็มที่ (Full Bloom) และเสริมการโจมตีระยะไกล',
    playstyle: {
      archetype: 'ทีมระยะไกล เน้นหลบและฟื้นฟู', difficulty: 'เล่นง่าย–ปานกลาง', position: 'แนวหลัง', statFocus: 'DEX เป็นหลัก · WIS / CON เพื่อความอยู่รอด',
      oneLine: 'สะสม Bloom เพื่อพยุงทีม เปลี่ยนเป็น Full Bloom แล้วใช้ความได้เปรียบของการโจมตีระยะไกลกับดาเมจ Radiant ปิดศัตรู',
      coreLoop: ['แจก Bloom ตอนเริ่มการต่อสู้', 'ประคองทีมด้วย Heal และ Regeneration', 'เร่งเข้าสู่ Full Bloom', 'ใช้ Ranged Advantage, Radiant Damage และ Blinded คุมการตอบโต้'],
      team: [
        ['แนวหน้าหลบหรือรับได้นาน', '1–2 ตัว', 'ซื้อเวลาให้ Bloom ฟื้น HP ตัวที่มี AC สูง ลดดาเมจ หรือสร้าง Reaction ป้องกันทีมเหมาะมาก'],
        ['แนวหลังโจมตีระยะไกล', '2–4 ตัว', 'Full Bloom ให้ความได้เปรียบกับ Ranged Attack จึงควรให้พื้นที่กับตัวโจมตีไกลที่มี Part แข็งแรง'],
        ['ตัวเสริมการอยู่รอด', '1 ตัว', 'การเพิ่ม AC, Concealment, ลดดาเมจ หรือฟื้นฟู ช่วยให้แผนยื้อและฮีลทำงานต่อเนื่อง'],
        ['พื้นที่สนับสนุน', 'ห้องจอมมาร', 'วางแหล่งเพิ่ม AC/ลดดาเมจ/ฟื้นฟูใกล้ห้องจอมมาร เพื่อเสริม Garden Defense และการต่อสู้นาน'],
      ],
      goodFits: ['มอนสเตอร์ DEX แบบโจมตีไกลหรือหลบเก่ง', 'ตัวอย่างแนวรับที่มีข้อมูลแล้ว: Arachne ใช้ Web Dome รับเวทพื้นที่และควบคุมแนวหน้า', 'สถานะที่ช่วยทีม: Bloom, Full Bloom, Regeneration, Blinded, Faerie Fire'],
      recommendedMonsters: [['Arachne', 'STR · แนวหน้า', 'ควบคุมด้วย Web และรับเวทพื้นที่แทนทีม'], ['Pegasus', 'DEX · Piercing/Radiant', 'ใช้ DEX และชนิดดาเมจเข้ากับธีม Aura'], ['Harpy', 'DEX · Piercing', 'ตัวเลือก DEX ช่วงต้นสำหรับแนวโจมตี'], ['Lesser Air Elemental', 'DEX · Piercing', 'เริ่มสร้างทีม DEX ได้ตั้งแต่ Tier 1'], ['Sylph', 'DEX · Slashing', 'เพิ่มดาเมจอีกชนิดให้ทีม DEX'], ['Ratatoskr', 'DEX · Physical', 'ตัวเลือก Tier 1 ที่ใช้ DEX และหาได้เร็ว']],
      authorityPlan: [['ช่วงตั้งทีม', 'Healing Wind / Rapid Bloom', 'เติม Bloom ให้ทีมและเร่งแกนหลักโดยไม่ต้องรอหลาย Combat'], ['ช่วงยื้อ', "Garden Defense / Nature's Cycle", 'ทำห้องจอมมารให้เป็นพื้นที่ยื้อและตอบโต้เมื่อถูกโจมตี'], ['ตัวปิดไฟต์', 'Dawn of Eden / Solar Storm', 'รีเซ็ต HP พร้อม Full Bloom หรือโจมตีหมู่และทำให้ศัตรูตาบอด']],
      phases: [['ต้น Run', 'หาแนวหน้าที่ไม่ล้มง่ายและตัวโจมตีระยะไกลก่อน ความอยู่รอดสำคัญกว่าการรีบเก็บแต่ DEX'], ['กลาง Run', 'เพิ่ม AC, Damage Reduction และความถี่การฟื้นฟู แล้วค่อยเร่ง Full Bloom ให้พร้อมกันหลายตัว'], ['ท้าย Run', 'เตรียมคำตอบต่อ Heal Block, Silenced และการโจมตีแนวหลัง เพราะสามอย่างนี้ตัดวงจรยื้อของ Aura โดยตรง']],
      pitfalls: ['มีแต่ฮีลแต่ไม่มีตัวทำดาเมจจบไฟต์', 'ใช้ทีมประชิดล้วนจนเสียประโยชน์จาก Full Bloom', 'ละเลย AC และ Damage Reduction เพราะการฟื้นฟูอย่างเดียวรับ Burst ไม่ไหว', 'ไม่เตรียมรับ Heal Block หรือ Silenced', 'บังคับเลือก DEX แม้ตัวที่ได้จะมี Part อ่อนกว่าตัว Stat อื่นมาก'],
      confidence: 'แกน Bloom/Full Bloom อ้างอิง Wiki; แนวทีมหลบและฟื้นฟูสอดคล้องกับตัวอย่างเคลียร์ Trial 21 ของชุมชน แต่ไม่ใช่สูตรตายตัว',
    },
    skills: [
      ['A', 'Enhanced Shot (T3)', 'ยิงเสริมพลัง (T3)', 'การโจมตีพื้นฐาน', 'ยิงศัตรูจากระยะไกลและสร้างความเสียหายเจาะแทง'],
      ['B', "Wind's Guidance", 'สายลมนำทาง', 'คุณลักษณะติดตัว', 'เมื่อเริ่มการต่อสู้ มอบผลิบาน (Bloom) 2 สแต็กให้ฝ่ายเราทั้งหมด'],
      ['M', 'Yggdrasil Bow', 'ธนูอิกดราซิล', 'ชิ้นส่วนหลัก', 'สร้างความเสียหายเจาะแทงและเรเดียนต์ พร้อมทำให้เป้าหมายติดเพลิงภูต (Faerie Fire)'],
      ['S1', 'Whisper of the Forest', 'เสียงกระซิบแห่งพงไพร', 'ชิ้นส่วนเสริม', 'เมื่อผลิบาน (Bloom) ฟื้นฟู HP ให้ Aura จะได้รับสังเคราะห์แสง (Photosynthesis)'],
      ['S2', "Sylph's Boots", 'รองเท้าบูตแห่งซิลฟ์', 'ชิ้นส่วนเสริม', 'เมื่อเข้าสู่เบ่งบานเต็มที่ (Full Bloom) จะตอบโต้ด้วยการทำให้ศัตรูทั้งหมดตาบอด (Blinded)'],
    ],
    authorities: [
      ['Healing Wind', 'สายลมเยียวยา', 'ฟื้นฟูกลุ่มฝ่ายเราที่มีสัดส่วน HP ต่ำที่สุดและมอบผลิบาน (Bloom) 3 สแต็ก'],
      ['Grasping Vine', 'เถาวัลย์พันธนาการ', 'สร้างเถาวัลย์หนาม (Thorn Vine) ในห้องกับดักแบบสุ่ม ทำความเสียหายเจาะแทงและมีโอกาสตรึงรากศัตรู'],
      ['Sunbeam', 'ลำแสงสุริยัน', 'ส่งลำแสงติดตามกลุ่มศัตรูที่อยู่ใกล้ที่สุด'],
      ['Rapid Bloom', 'ผลิบานฉับพลัน', 'มอบผลิบาน (Bloom) 5 สแต็กให้ฝ่ายเราทุกตัวที่ยังไม่ได้อยู่ในเบ่งบานเต็มที่ (Full Bloom)'],
      ['Healing Rain', 'พิรุณเยียวยา', 'มอบฟื้นฟูต่อเนื่อง (Regeneration) ให้กลุ่มฝ่ายเราที่มีสัดส่วน HP ต่ำที่สุด'],
      ['Garden Defense', 'สวนพิทักษ์', 'สร้างพื้นที่ Garden Defense ภายในห้องจอมมาร'],
      ["Nature's Cycle", 'วัฏจักรแห่งธรรมชาติ', 'มอบเอฟเฟกต์ที่ทำให้การรับความเสียหายสร้างผลิบาน (Bloom) และโจมตีศัตรูในพื้นที่เดียวกัน'],
      ['Dawn of Eden', 'รุ่งอรุณแห่งเอเดน', 'ฟื้นฟู HP ฝ่ายเราทั้งหมดจนเต็มและทำให้เข้าสู่เบ่งบานเต็มที่ (Full Bloom) ทันที'],
      ['Solar Storm', 'พายุสุริยะ', 'โจมตีศัตรูทั้งหมดด้วยความเสียหายเรเดียนต์และทำให้ตาบอด (Blinded) แบบถาวร'],
    ],
    relics: ['Morning Dew', 'Nutrient Injection', 'Co-existing Garden', 'Eternal Sun'],
    sourceUpdated: '29 ก.ค. 2026', tone: 'green',
  },
  {
    slug: 'rhea', name: 'Rhea', tagline: 'จักรพรรดินีแห่งสัตว์ร้าย ผู้นำด้วยความดุดัน',
    unlock: "Architect's Workshop หลังปลด Dark Lord's Quarters", core: 'ความกล้าหาญ (Valor)', keyStat: 'STR', damage: ['Slashing', 'Lightning'],
    stats: { STR: 18, DEX: 12, CON: 18, INT: 6, WIS: 12, CHA: 12, HP: 105, AC: 10, Initiative: 0 },
    immunity: 'หวาดกลัว (Fear)', theme: 'สร้างความกล้าหาญ (Valor) เพื่อป้องกันแนวหน้าและเสริมความเสียหายเมื่อโจมตี',
    playstyle: {
      archetype: 'ทีมแนวหน้าบุกแลกด้วย Valor', difficulty: 'ปานกลาง–สูง', position: 'แนวหน้า', statFocus: 'STR เป็นหลัก · CON รอง · ค่ารอดชีวิตตามสถานการณ์',
      oneLine: 'ให้ Rhea และแนวหน้ารับแรงปะทะเพื่อสร้าง Valor แล้วเปลี่ยนสแต็กเป็น HP ชั่วคราว ความได้เปรียบ และดาเมจสายฟ้า',
      coreLoop: ['เริ่มการบุกด้วย Valor', 'ให้แนวหน้ารับและโจมตีเพื่อหมุนสแต็ก', 'คุมทางเข้าด้วย Prone / Stun / Lightning', 'เร่ง Valor ทั้งทีมก่อนกด Ragnarok ปิดคลื่น'],
      team: [
        ['Rhea แนวหน้า', 'ตำแหน่งหลัก', 'สกิลของเธอทำงานกับการโจมตีและรับดาเมจ จึงควรย้าย Rhea ไปแถวหน้าของ Group A เว้นแต่ด่านนั้นโฟกัสเธอหนักเกินไป'],
        ['แทงก์หรือผู้พิทักษ์คู่', '1–2 ตัว', 'ช่วยแบ่งแรงปะทะและกันไม่ให้ Rhea ถูก Focus คนเดียว ตัวที่มี Redirect หรือ Damage Reduction เหมาะมาก'],
        ['ตัวโจมตี STR', '2–3 ตัว', 'รับประโยชน์จากการเน้น STR และใช้ Valor เพิ่มดาเมจเมื่อโจมตีโดน แต่ควรมีตัวโจมตีระยะไกลสำรองหนึ่งตำแหน่ง'],
        ['ตัวสนับสนุนแนวหลัง', '1–2 ตัว', 'ฮีล เพิ่ม AC ป้องกันเวท หรือคุมศัตรู เพื่อไม่ให้ทีมบุกแลกพังจาก Burst และ Spell'],
      ],
      goodFits: ['มอนสเตอร์ STR: Tiger, Wendigo, Sprout Soldier, Kelpie, Salamander, Ugallu, Hydra, Fenrir, Sleipnir, Behemoth', 'ตัวอย่างที่มีข้อมูลแล้ว: Wendigo ช่วยรับการโจมตีแทน ลดดาเมจ และ Stun', 'สถานะที่ช่วยทีม: Valor, Lightning Shield, Prone, Stun, Lightning Enchant'],
      recommendedMonsters: [['Wendigo', 'STR · แทงก์', 'รับการโจมตีแทน ลดดาเมจ และสร้าง Stun'], ['Tiger', 'STR · Slashing', 'ตัวทำดาเมจ STR ช่วงต้นที่เข้ากับการเน้น Stat'], ['Ugallu', 'STR · Bludgeoning', 'แนวหน้าระดับกลางที่เพิ่มชนิดดาเมจให้ทีม'], ['Hydra', 'STR · Slashing', 'ตัวทำดาเมจ STR ระดับสูงสำหรับช่วงท้าย Run'], ['Fenrir', 'STR · Slashing', 'ตัวโจมตี STR Tier สูงสำหรับทีมบุก'], ['Behemoth', 'STR · Bludgeoning', 'แนวหน้า Tier 9 และดาเมจกระแทกสำหรับท้ายเกม']],
      authorityPlan: [['ช่วงตั้งทีม', 'Unyielding Command / Current Shield', 'เติม Valor ให้แนวหน้าและเพิ่มการทอยต้านทานหรือสะท้อนความเสียหาย'], ['ช่วงตั้งรับหน้าห้อง', "King's Audience / Lion King's Roar", 'หยุดศัตรูที่เข้าห้องและเติม Valor/HP ชั่วคราวให้ทั้งทีม'], ['ตัวปิดไฟต์', 'Ragnarok', 'โจมตีศัตรูทั้งหมดและเสริมสายฟ้าให้ฝ่ายเรากับกับดัก']],
      phases: [['ต้น Run', 'ย้าย Rhea ไปแนวหน้า หาแทงก์คู่และตัวใช้ STR ที่ทำดาเมจสม่ำเสมอ อย่าวางตัวประชิดมากจนไม่มีพื้นที่รับศัตรู'], ['กลาง Run', 'เสริมการฮีล ลดดาเมจ และ Save Against Spell เพื่อแก้จุดอ่อนของทีมแนวหน้า พร้อมเพิ่มแหล่ง Stun/Prone'], ['ท้าย Run', 'เตรียมตำแหน่งสำรองหากบอส Focus Rhea และมีดาเมจชนิดอื่นเผื่อศัตรูต้าน Slashing/Lightning']],
      pitfalls: ['ปล่อย Rhea อยู่แนวหลังจนสกิลรับดาเมจและ Valor ทำงานไม่เต็มที่', 'ให้ Rhea รับ Focus คนเดียวโดยไม่มีแทงก์คู่หรือฮีล', 'สร้างทีม STR ล้วนแต่ไม่มีคำตอบต่อเวทหรือแนวหลัง', 'ใช้ Valor ไม่ทันก่อนคลื่นใหญ่', 'เกิน Dominance เพราะใส่ตัวแนวหน้ามากเกินจำเป็น'],
      confidence: 'แกน Valor อ้างอิง Wiki; ตำแหน่งแนวหน้าและโครง STR เป็นคำแนะนำจากชุมชนซึ่งควรปรับตาม Trial และ Patch',
    },
    skills: [
      ['A', 'Basic Slash', 'ฟันพื้นฐาน', 'การโจมตีพื้นฐาน', 'ฟันศัตรูและสร้างความเสียหายฟัน'],
      ['B', "Lion King's Heart", 'หัวใจราชสีห์', 'คุณลักษณะติดตัว', 'ได้รับความกล้าหาญ (Valor) 5 สแต็กเมื่อเริ่มการบุก และอีก 2 สแต็กเมื่อเริ่มการต่อสู้'],
      ['M', 'Golden Zweihander', 'ดาบสองมือทองคำ', 'ชิ้นส่วนหลัก', 'เมื่อโจมตีโดน จะมอบความกล้าหาญ (Valor) ให้ฝ่ายเราทั้งหมด'],
      ['S1', 'Armor of Valor', 'เกราะแห่งความกล้า', 'ชิ้นส่วนเสริม', 'ได้รับความกล้าหาญ (Valor) เมื่อรับความเสียหาย และได้เปรียบในการทอยโจมตีเมื่อมีตั้งแต่ 5 สแต็ก'],
      ['S2', 'Command Aura', 'รัศมีบัญชาการ', 'ชิ้นส่วนเสริม', 'ทุกต้นเทิร์นมอบความกล้าหาญ (Valor) ให้แนวหน้า หากเต็มจะฟื้นฟู HP แทน'],
    ],
    authorities: [
      ['Judgement', 'พิพากษา', 'โจมตีแถวหน้าของกลุ่มศัตรูแบบสุ่มด้วยความเสียหายสายฟ้า'],
      ['Thunderous Command', 'บัญชาสายฟ้าคำราม', 'โจมตีกลุ่มศัตรูแบบสุ่มด้วยความเสียหายฟ้าร้องและทำให้ล้มลง (Prone)'],
      ['Overload', 'ประจุเกินขีด', 'ทำให้กลุ่มศัตรูแบบสุ่มติดประจุเกินขีด (Overload)'],
      ['Unyielding Command', 'บัญชาไม่ย่อท้อ', 'มอบ Valor 4 สแต็กและความได้เปรียบในการทอยต้านทานให้แถวหน้าฝ่ายเรา'],
      ['Current Shield', 'โล่กระแสไฟ', 'มอบความกล้าหาญ (Valor) และโล่สายฟ้า (Lightning Shield) ซึ่งสะท้อนความเสียหายกลับผู้โจมตี'],
      ["King's Audience", 'เข้าเฝ้าราชัน', 'ทำให้ศัตรูที่เข้าห้องจอมมารมึนงง (Stun) และได้รับความเสียหายสายฟ้า'],
      ['Death Lightning', 'อัสนีมรณะ', 'สร้างสภาพแวดล้อมที่ผ่าสายฟ้าใส่พื้นที่สุ่มซึ่งไม่มีฝ่ายเราอยู่'],
      ["Lion King's Roar", 'เสียงคำรามราชสีห์', 'มอบ Valor 10 สแต็กและ HP ชั่วคราวให้ฝ่ายเราทั้งหมด'],
      ['Ragnarok', 'วันสิ้นโลก', 'โจมตีศัตรูทั้งหมดด้วยความเสียหายสายฟ้า และเสริมสายฟ้าให้ฝ่ายเรากับกับดักทั้งหมด'],
    ],
    relics: ['Horn of Valor', 'Endless Fervor', 'Sword of Judgement', "Lion King's Crown"],
    sourceUpdated: '29 ก.ค. 2026', tone: 'gold',
  },
] as const;

export const coreSystems = [
  ['Run Setup', 'ก่อนเริ่ม Run', 'เลือกจอมมาร สกิน แคมเปญ และบททดสอบ'],
  ['Node Map', 'ระหว่าง Run', 'เลือก Battle, Merchant, Event หรือจุดพัฒนาในแต่ละวัน'],
  ['Dungeon Layout', 'ระหว่าง Run', 'วางมอนสเตอร์ สนามล่า กับดัก และโครงสร้างสนับสนุน'],
  ['Combat', 'ระหว่าง Run', 'ต่อสู้อัตโนมัติด้วยตำแหน่ง สกิล และการทอยค่าต่าง ๆ'],
  ['Monster Growth', 'ระหว่าง/ข้าม Run', 'Train, Promote, Fuse, Sacrifice และติดตั้ง Part'],
  ['Facility Growth', 'ระหว่าง/ข้าม Run', 'Modify, Promote, Combine, Attach และ Relocate'],
  ['Dark Lord Growth', 'ระหว่าง/ข้าม Run', 'Trait, Promotion, Ascension, Aspect และ Authority'],
  ['Ark of Memory', 'ข้าม Run', 'เก็บมอนสเตอร์ สิ่งปลูกสร้าง และข้อมูลบางส่วนไปใช้รอบถัดไป'],
  ["Architect's Workshop", 'นอก Run', 'ปลดล็อกฟังก์ชันและอัปเกรดถาวร'],
  ['Trials & Difficulty', 'ก่อน Run', 'ปรับความยากและรับรางวัล First Clear'],
] as const;

export const glossaryTerms = [
  ['Dark Lord', 'จอมมาร', 'ใช้ใน Wiki'], ['Monster', 'มอนสเตอร์', 'ใช้ใน Wiki'], ['Hero', 'ฮีโร่', 'ใช้ใน Wiki'],
  ['Run', 'รอบการเล่น', 'ใช้ใน Wiki'], ['Stage', 'ด่าน', 'ใช้ใน Wiki'], ['Campaign', 'แคมเปญ', 'ใช้ใน Wiki'],
  ['Trial', 'บททดสอบ', 'ใช้ใน Wiki'], ['Ark of Memory', 'Ark of Memory (คลังความทรงจำ)', 'คงอังกฤษ'],
  ["Architect's Workshop", "Architect's Workshop (เวิร์กช็อปสถาปนิก)", 'คงอังกฤษ'], ['Codex', 'สารานุกรม', 'ใช้ใน Wiki'],
  ['Promotion', 'เลื่อนขั้น', 'ใช้ใน Wiki'], ['Ascension', 'จุติ', 'ใช้ใน Wiki'], ['Aspect', 'Aspect (แอสเปกต์)', 'คงอังกฤษ'],
  ['Part', 'ชิ้นส่วน', 'ใช้ใน Wiki'], ['Main Part', 'ชิ้นส่วนหลัก', 'ใช้ใน Wiki'], ['Sub Part', 'ชิ้นส่วนเสริม', 'ใช้ใน Wiki'],
  ['Relic', 'วัตถุโบราณ / ไอเทมเสริม', 'คงอังกฤษในชื่อหมวด'], ['Dream Dust', 'ผงความฝัน', 'คงอังกฤษในหน้าระบบ'], ['Chest', 'หีบรางวัล', 'ใช้ใน Wiki'],
  ['Ethereal Part', 'Ethereal Part (ชิ้นส่วนชั่วคราว)', 'ต้องตรวจในเกม'], ['Skill', 'สกิล', 'ใช้ใน Wiki'],
  ['Ability', 'ความสามารถ', 'ใช้ใน Wiki'], ['Authority', 'อำนาจจอมมาร', 'ใช้ใน Wiki'], ['Trait', 'คุณลักษณะ', 'ใช้ใน Wiki'],
  ['Facility', 'สิ่งปลูกสร้าง', 'ใช้ใน Wiki'], ['Hunting Ground', 'สนามล่า', 'ใช้ใน Wiki'], ['Trap', 'กับดัก', 'ใช้ใน Wiki'],
  ['Structure', 'โครงสร้างสนับสนุน', 'ใช้ใน Wiki'], ['Dominance', 'ค่าควบคุม', 'ใช้ใน Wiki'], ['Durability', 'ความทนทาน', 'ใช้ใน Wiki'],
  ['Status Effect', 'เอฟเฟกต์สถานะ', 'ใช้ใน Wiki'], ['Buff', 'บัฟ', 'ใช้ใน Wiki'], ['Debuff', 'ดีบัฟ', 'ใช้ใน Wiki'],
  ['Stack', 'สแต็ก / จำนวนสะสม', 'ใช้ใน Wiki'], ['Cooldown', 'เวลารอใช้', 'ใช้ใน Wiki'], ['Attack Roll', 'ทอยโจมตี', 'ใช้ใน Wiki'],
  ['Saving Throw', 'ทอยต้านทาน', 'ใช้ใน Wiki'], ['Difficulty Class', 'ค่าความยาก (DC)', 'ใช้ใน Wiki'],
  ['Armor Class', 'ค่าป้องกัน (AC)', 'ใช้ใน Wiki'], ['Initiative', 'ลำดับการลงมือ', 'ใช้ใน Wiki'],
  ['Resistance', 'ต้านทาน', 'ใช้ใน Wiki'], ['Immunity', 'ป้องกันโดยสมบูรณ์', 'ใช้ใน Wiki'], ['Vulnerability', 'แพ้ทาง', 'ใช้ใน Wiki'],
] as const;

export const projectSources = [
  { level: 'A', title: 'GameCoaster Release Notes', type: 'ทางการ', url: 'https://gamecoaster.notion.site/Dungeon-Within-Release-Note-EN-32e4966ac9c3808bba34f56a92457d39', use: 'Patch, Build และระบบใหม่' },
  { level: 'A', title: 'Apple App Store', type: 'ทางการ', url: 'https://apps.apple.com/us/app/dungeon-within/id6761328517', use: 'เวอร์ชันเผยแพร่และประวัติอัปเดต' },
  { level: 'A', title: 'Google Play', type: 'ทางการ', url: 'https://play.google.com/store/apps/details?id=com.GameCoaster.DungeonWithin', use: 'ข้อมูลเกมและเวอร์ชัน Android' },
  { level: 'B', title: 'ข้อมูลภายในเกม', type: 'หลักฐานตรง', url: '', use: 'ค่าสถานะ สกิล และเงื่อนไขจริงใน Build ปัจจุบัน' },
  { level: 'C', title: 'Dungeon Within Wiki', type: 'ชุมชน / CC BY-SA 4.0', url: 'https://dungeonwithin.miraheze.org/wiki/Main_Page', use: 'ดัชนีข้อมูลและข้อมูลตั้งต้น' },
  { level: 'D', title: 'r/Dungeon_Within', type: 'ชุมชน', url: 'https://www.reddit.com/r/Dungeon_Within/', use: 'เทคนิค Build และประเด็นที่ต้องทดสอบ' },
] as const;

export const roadmapPhases = [
  { id: '1.1', title: 'แหล่งข้อมูล', status: 'done', output: 'จัดระดับแหล่งข้อมูลและตรวจ CC BY-SA 4.0' },
  { id: '1.2', title: 'มาตรฐานคำแปล', status: 'done', output: 'กำหนดศัพท์ไทย–อังกฤษมากกว่า 100 คำ' },
  { id: '1.3', title: 'โครงสร้างข้อมูล', status: 'done', output: 'กำหนด Schema, Source และ Verification' },
  { id: '2.1', title: 'ระบบหลัก', status: 'done', output: 'ทำบัญชีระบบก่อน Run, ใน Run และข้าม Run' },
  { id: '2.1b', title: 'ระบบค่าสถานะ', status: 'done', output: 'อธิบาย STR–CHA, Key Stat, Modifier และ Roll' },
  { id: '2.2', title: 'จอมมาร', status: 'done', output: 'สำรวจ Desponia, Aura และ Rhea' },
  { id: '2.2b', title: 'คำแปลสกิลจอมมาร', status: 'done', output: 'แปล Skill, Part และ Authority รวม 42 รายการ' },
  { id: '2.2c', title: 'พจนานุกรมสถานะ', status: 'done', output: 'แปลสถานะแกนของจอมมาร 24 รายการ' },
  { id: '2.2d', title: 'แนวทางเล่นจอมมาร', status: 'done', output: 'เพิ่มโครงทีม แผนการเล่น และข้อควรระวังของจอมมารทั้ง 3 ตัว' },
  { id: '2.3a', title: 'บัญชีมอนสเตอร์', status: 'done', output: 'รวบรวม 76 ตัว แบ่ง Tier 1–9' },
  { id: '2.3b', title: 'มอนสเตอร์ต้นแบบ', status: 'done', output: 'แปลสกิลและลงรายละเอียด Wendigo, Arachne, Transcendent' },
  { id: '2.3c', title: 'คำแปลมอนสเตอร์ Tier 1–3', status: 'done', output: 'แปล 130 ชื่อจากมอนสเตอร์ 26 ตัว พร้อมหน้าค้นหาและกรอง' },
  { id: '2.4', title: 'ห้องและกับดัก', status: 'done', output: 'รวบรวม 41 รายการ แบ่งสนามล่า กับดัก และโครงสร้าง พร้อมสูตรและคำเตือน' },
  { id: '2.4b', title: 'แนวทางจัดผังและชุดกับดัก', status: 'done', output: 'เพิ่มผัง 3×3 หลักวางห้อง ชุดตามจอมมาร และคู่ห้องแนะนำ' },
  { id: '2.5', title: 'ไอเทมและอุปกรณ์', status: 'done', output: 'รวบรวม Relic 59 ชิ้น และอธิบายช่อง Part, วิธีหา, Dominance และ Ark' },
  { id: '2.5b', title: 'Demon Lord Relics', status: 'done', output: 'นำเข้า War of the Gods 28 ชิ้น แยก Tania, Lilith และ Meryelle' },
  { id: '2.6', title: 'ศัตรูและผู้บุกรุก', status: 'next', output: 'ขั้นถัดไป: ทำบัญชีประเภท ความสามารถ และจุดอ่อนของผู้บุกรุก' },
] as const;
