'use client';

import { useMemo, useState } from 'react';
import SiteHeader, { SiteFooter } from '../../components/site-header';
import { relics, relicCounts, type RelicGroup, type RelicRarity } from '../../items-data';

const groups: Array<'ทั้งหมด' | RelicGroup> = ['ทั้งหมด', 'ทั่วไป', 'จอมมาร', 'อีเวนต์', 'Demon Lord'];
const rarities: Array<'ทุกระดับ' | RelicRarity> = ['ทุกระดับ', 'Normal', 'Rare', 'Epic', 'Legendary'];

export default function ItemsPage() {
  const [query, setQuery] = useState('');
  const [group, setGroup] = useState<(typeof groups)[number]>('ทั้งหมด');
  const [rarity, setRarity] = useState<(typeof rarities)[number]>('ทุกระดับ');
  const results = useMemo(() => {
    const term = query.trim().toLocaleLowerCase('th');
    return relics.filter((entry) => {
      const matchesGroup = group === 'ทั้งหมด' || entry.group === group;
      const matchesRarity = rarity === 'ทุกระดับ' || entry.rarity === rarity;
      const text = `${entry.name} ${entry.nameTh} ${entry.summary} ${entry.owner ?? ''} ${entry.tags.join(' ')}`.toLocaleLowerCase('th');
      return matchesGroup && matchesRarity && (!term || text.includes(term));
    });
  }, [query, group, rarity]);

  return <main className="hub-page"><SiteHeader />
    <section className="data-hero items-hero"><p className="breadcrumbs"><a href="/wiki">คลังข้อมูล</a><span>/</span>ไอเทมและอุปกรณ์</p><p className="eyebrow"><span /> Phase 2.5 · 2.5b</p><h1>Relic และ Part<br />ใช้ต่างกันอย่างไร?</h1><p>คลังไอเทมเสริมทั้งดันเจี้ยนและคู่มืออุปกรณ์สกิลของมอนสเตอร์ พร้อมวิธีได้มา ช่องติดตั้ง และสิ่งที่ต้องระวังเรื่อง Dominance</p><div className="data-warning"><b>สถานะข้อมูล</b><span>แปลจาก Relics และ Parts ของ Wiki ชุมชน ตัวเลขที่เปลี่ยนตามระดับ Relic หรือ Patch ควรตรวจซ้ำในเกม v0.6.0</span></div></section>
    <section className="hub-content items-content">
      <div className="item-summary"><article><span>◆</span><div><small>Relics</small><b>{relicCounts.total} ชิ้นในคลัง</b><p>รวม Relic ปกติ อีเวนต์ จอมมาร และชุด War of the Gods</p></div></article><article><span>M</span><div><small>Monster Parts</small><b>237 Part ที่สลับได้</b><p>เปลี่ยนสกิลและหน้าที่ของมอนสเตอร์ แต่ต้องติดให้ตรงประเภทช่อง</p></div></article><article><span>5</span><div><small>Skill slots</small><b>A · B · M · S1 · S2</b><p>A/B ติดมากับยูนิต ส่วน M/S1/S2 เป็นช่องสำหรับ Part ระหว่าง Run</p></div></article></div>

      <section className="item-difference"><div className="section-title-row"><h2>แยก Relic กับ Part ก่อน</h2><span>สองระบบนี้ทำหน้าที่คนละระดับ</span></div><div><article className="relic"><span>◆</span><div><small>ไอเทมระดับดันเจี้ยน</small><h3>Relic</h3><p>ให้ผลกับทรัพยากร จอมมาร มอนสเตอร์ ห้อง หรือกฎของ Run โดยไม่ต้องนำไปเสียบในช่องสกิลของยูนิต</p><b>หาได้จาก Chest · Merchant · Event · Battle Reward</b></div></article><article className="part"><span>M</span><div><small>อุปกรณ์สกิลของยูนิต</small><h3>Part</h3><p>เพิ่มหรือเปลี่ยนสกิลในช่อง M, S1 และ S2 ของมอนสเตอร์หรือจอมมาร และเพิ่ม Dominance Cost ให้ยูนิตนั้น</p><b>หาได้จาก Merchant · Dismantle · Sanctuary · Event</b></div></article></div></section>

      <section className="part-flow" id="part-basics"><div className="section-title-row"><div><p className="eyebrow"><span /> เข้าใจใน 5 ขั้น</p><h2>Part ทำงานอย่างไรในหนึ่ง Run?</h2></div><span>เริ่มจากช่องว่าง แล้วประกอบ Build ระหว่างทาง</span></div><div className="part-flow-grid"><article><b>1</b><small>เริ่มต้น</small><h3>มอนสเตอร์มี A และ B</h3><p>การโจมตีพื้นฐานกับคุณลักษณะติดตัวมากับตัว ส่วนช่อง M, S1 และ S2 ยังว่าง</p></article><article><b>2</b><small>ค้นหา</small><h3>รับ Part ระหว่าง Run</h3><p>หาได้จาก Merchant, Dismantle, Search ที่ Sanctuary หรือบาง Event แต่ Part ประจำตัวไม่ได้ออกแน่นอน</p></article><article><b>3</b><small>ผสม Build</small><h3>ยืมจากตัวอื่นได้</h3><p>Part ไม่ได้ล็อกกับเจ้าของเดิม จึงนำสกิลของมอนสเตอร์อื่นมาประกอบให้เข้ากับ Stat และหน้าที่ใหม่ได้</p></article><article><b>4</b><small>ติดตั้ง</small><h3>เลือกให้ตรงประเภทช่อง</h3><p>Main Part ลงได้เฉพาะ M ส่วน Sub Part ลง S1 หรือ S2 ช่องใดก็ได้</p></article><article><b>5</b><small>ตัดสินใจ</small><h3>ชั่งพลังกับ Dominance</h3><p>Part เพิ่มต้นทุนของยูนิต หาก Build ดีให้เก็บมอนสเตอร์พร้อม Part ไว้ข้าม Run ผ่าน Ark of Memory</p></article></div><p className="part-flow-note"><b>จำง่าย:</b> A/B คือพื้นฐานของตัวละคร · M/S1/S2 คือช่องปรับแต่ง · Part ข้ามมอนสเตอร์ได้ แต่ข้ามประเภท Main/Sub ไม่ได้</p></section>

      <section className="part-guide"><div className="section-title-row"><div><p className="eyebrow"><span /> Equipment guide</p><h2>อ่านช่อง Part ทั้ง 5</h2></div><span>ตำแหน่งช่องสำคัญกว่าชื่อ Part</span></div><div className="part-slots"><article className="innate"><b>A</b><h3>Base Attack</h3><p>การโจมตีพื้นฐานที่ติดมากับยูนิต ไม่ใช่ช่องสำหรับ Part ที่เก็บระหว่าง Run</p></article><article className="innate"><b>B</b><h3>Innate Trait</h3><p>คุณลักษณะติดตัวเริ่มต้นของยูนิต และไม่ใช่ช่องว่างสำหรับติด Part</p></article><article className="main"><b>M</b><h3>Main Part</h3><p>ใส่ได้เฉพาะ Main Part และมักเป็นสกิลหลักที่เปลี่ยนบทบาทของยูนิตอย่างชัดเจน</p></article><article className="sub"><b>S1</b><h3>Sub Part 1</h3><p>ช่องสกิลเสริม สามารถรับ Sub Part จากช่อง S1 หรือ S2 ได้</p></article><article className="sub"><b>S2</b><h3>Sub Part 2</h3><p>ช่องสกิลเสริมอีกช่อง และสามารถใส่ Sub Part ชนิดเดียวกับ S1 ซ้ำได้หากมี</p></article></div><div className="part-rule-grid"><article><b>ติดให้ตรงประเภท</b><p>Main Part ใส่ได้เฉพาะช่อง M แต่ Sub Part ใส่ได้ทั้ง S1 และ S2</p></article><article><b>คิด Dominance เพิ่ม</b><p>Part ทุกชิ้นเพิ่มต้นทุนของยูนิต หากเกิน Max Dominance จะเสีย HP, Durability และ Roll</p></article><article><b>ตรวจ Stat และเงื่อนไข</b><p>Part อาจใช้ Stat ที่ยูนิตมีต่ำ หรือต้องการสถานะที่มีเพียงเจ้าของเดิมสร้างได้</p></article><article><b>Ark เก็บ Part ที่ติดอยู่</b><p>มอนสเตอร์ใน Ark of Memory จะเก็บ Part ที่ติดตั้ง และใช้ Transfer ย้ายระหว่างมอนสเตอร์ใน Ark ได้</p></article></div></section>

      <section className="part-checklist"><div><p className="eyebrow"><span /> ก่อนกดติดตั้ง</p><h2>เช็ก Part ด้วยคำถาม 4 ข้อ</h2></div><ol><li><b>01</b><span><strong>ช่องตรงหรือไม่?</strong><small>M ต้องลง M ส่วน Sub ลง S1 หรือ S2</small></span></li><li><b>02</b><span><strong>ใช้ Stat ตัวไหน?</strong><small>ดู Based on STR–CHA และ Modifier ของผู้ใส่</small></span></li><li><b>03</b><span><strong>เงื่อนไขเกิดจริงไหม?</strong><small>ตรวจสถานะ ระยะ ตำแหน่ง และ Reaction ที่สกิลต้องการ</small></span></li><li><b>04</b><span><strong>Dominance ยังไม่เกิน?</strong><small>รวมค่าของยูนิตและ Part ก่อนเข้าการต่อสู้</small></span></li></ol></section>

      <section className="demon-relic-overview"><div className="section-title-row"><div><p className="eyebrow"><span /> War of the Gods</p><h2>Demon Lord Relics</h2><p>Relic Legendary เฉพาะแคมเปญ 28 ชิ้น ซึ่งไม่แสดงรวมกับ Relic ปกติใน Codex ของเกม</p></div><span>เลือกตัวกรอง “Demon Lord” เพื่อดูทั้งหมด</span></div><div className="demon-lord-relic-grid"><article className="tania"><span>T</span><div><small>แกน Fire · Burn · Overheat</small><h3>Tania</h3><p>10 ชิ้น เน้นเพิ่มลูกเต๋าไฟ เร่ง Burn และเปลี่ยนกับดักหรือห้องจอมมารให้เป็นจุดระเบิดความเสียหาย</p></div></article><article className="lilith"><span>L</span><div><small>แกน Psychic · Charm · Euphoria</small><h3>Lilith</h3><p>10 ชิ้น เน้น CHA, Charmed, Euphoria และเศรษฐกิจ ทั้งการรับ Dream Dust และซื้อของฟรี</p></div></article><article className="meryelle"><span>M</span><div><small>แกน Cold · Chill · Frostbite</small><h3>Meryelle</h3><p>8 ชิ้น เน้นเพิ่มลูกเต๋าความเย็น สะสม Chill/Frostbite และเสริมความอยู่รอดให้ทั้งทีม</p></div></article></div></section>

      <section className="relic-catalog" id="relic-catalog"><div className="section-title-row"><div><p className="eyebrow"><span /> Relic archive</p><h2>รายการ Relic ทั้งหมด</h2><p>แสดง {results.length} จาก {relicCounts.total} ชิ้น</p></div><span>รวม War of the Gods {relicCounts.campaign} ชิ้น</span></div><div className="relic-tools"><label><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ค้นชื่อ ผลลัพธ์ Stat หรือระบบที่เกี่ยวข้อง..." aria-label="ค้นหา Relic" /></label><select value={rarity} onChange={(event) => setRarity(event.target.value as (typeof rarities)[number])} aria-label="กรองความหายาก">{rarities.map((item) => <option key={item}>{item}</option>)}</select></div><div className="relic-group-tabs" role="group" aria-label="กรองประเภท Relic">{groups.map((item) => <button className={group === item ? 'active' : ''} onClick={() => setGroup(item)} key={item}>{item}<small>{item === 'ทั้งหมด' ? relicCounts.total : item === 'ทั่วไป' ? relicCounts.regular : item === 'จอมมาร' ? relicCounts.darkLord : item === 'อีเวนต์' ? relicCounts.event : relicCounts.campaign}</small></button>)}</div>{results.length ? <div className="relic-grid">{results.map((entry) => { const cardGroup = entry.group === 'ทั่วไป' ? 'regular' : entry.group === 'จอมมาร' ? 'lord' : entry.group === 'อีเวนต์' ? 'event' : 'campaign'; return <article className={`relic-card group-${cardGroup} rarity-${entry.rarity.toLocaleLowerCase()}`} key={entry.name}><div className="relic-card-head"><span>{entry.group === 'ทั่วไป' ? '◆' : entry.group === 'อีเวนต์' ? '✦' : entry.owner?.slice(0,1)}</span><div><small>{entry.group}{entry.owner ? ` · ${entry.owner}` : ''}</small><h3>{entry.name}</h3><p>{entry.nameTh}</p></div><b>{entry.rarity}</b></div><p className="relic-description">{entry.summary}</p><div className="relic-tags">{entry.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>{entry.caution && <p className="relic-caution"><b>รอตรวจ</b>{entry.caution}</p>}</article>; })}</div> : <div className="monster-empty"><b>ไม่พบ Relic ที่ตรงกัน</b><p>ลองลบคำค้นหรือเปลี่ยนตัวกรอง</p></div>}</section>
      <div className="inline-warning">ชื่อไทยเป็นคำแปลเพื่อช่วยอ่าน ไม่ใช่ชื่อภาษาไทยอย่างเป็นทางการในเกม รายการ Part ทั้ง 237 ชิ้นจะแสดงในหน้าของมอนสเตอร์เจ้าของ Part ตามโครง Wiki ต้นฉบับ</div>
    </section><SiteFooter />
  </main>;
}
