import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import SiteHeader, { SiteFooter } from '../../../components/site-header';
import { darkLords, monsterImagePath, monsters, prototypeMonsters } from '../../../content-data';

export function generateStaticParams() { return darkLords.map((lord) => ({ slug: lord.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params; const lord = darkLords.find((item) => item.slug === slug);
  return lord ? { title: `${lord.name} | Dungeon Within Thailand Wiki`, description: lord.theme, openGraph: { title: lord.name, description: lord.theme, images: [] }, twitter: { title: lord.name, description: lord.theme, images: [] } } : {};
}

export default async function DarkLordDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const lord = darkLords.find((item) => item.slug === slug); if (!lord) notFound();
  const statEntries = Object.entries(lord.stats);
  const communitySource = lord.slug === 'desponia' ? 'https://www.reddit.com/r/Dungeon_Within/comments/1uvjv49/best_team_desponia/' : lord.slug === 'aura' ? 'https://note.com/tender_spirea470/n/nefca086addda?hl=en' : 'https://www.reddit.com/r/Dungeon_Within/comments/1ui8kxx/who_said_rhea_was_weak_3/';
  return <main className="hub-page"><SiteHeader />
    <section className={`lord-detail-hero ${lord.tone}`}><div className="lord-detail-copy"><p className="breadcrumbs"><a href="/wiki">คลังข้อมูล</a><span>/</span><a href="/wiki/dark-lords">จอมมาร</a><span>/</span>{lord.name}</p><span className="status-pill review">NEEDS REVIEW · v0.6.0</span><h1>{lord.name}</h1><p>{lord.tagline}</p><div className="core-badge"><small>แกนกลไก</small><b>{lord.core}</b></div></div><div className="lord-detail-portrait"><img src={`/images/characters/dark-lords/${lord.slug}.png`} alt={`ภาพตัวละคร ${lord.name}`} /></div></section>
    <section className="detail-layout"><article className="detail-main">
      <section><h2>ภาพรวม</h2><p>{lord.theme}</p><div className="fact-grid"><div><small>ปลดล็อก</small><b>{lord.unlock}</b></div><div><small>Key Stat</small><b>{lord.keyStat}</b></div><div><small>Damage</small><b>{lord.damage.join(' / ')}</b></div><div><small>Immunity</small><b>{lord.immunity}</b></div></div></section>
      <section className="playstyle-guide" id="playstyle"><div className="section-title-row"><h2>แนวทางเล่นและจัดทีม</h2><span>Strategy Guide · คำแนะนำ</span></div><div className="guide-verdict"><div><small>รูปแบบทีมแนะนำ</small><h3>{lord.playstyle.archetype}</h3><p>{lord.playstyle.oneLine}</p></div><dl><div><dt>ความยาก</dt><dd>{lord.playstyle.difficulty}</dd></div><div><dt>ตำแหน่ง</dt><dd>{lord.playstyle.position}</dd></div><div><dt>เน้น Stat</dt><dd>{lord.playstyle.statFocus}</dd></div></dl></div>
        <div className="guide-label"><span>01</span><div><h3>วงจรการเล่นหลัก</h3><p>จำเป็นลำดับสั้น ๆ ก่อน แล้วค่อยปรับตามสิ่งที่ได้ใน Run</p></div></div><div className="core-loop">{lord.playstyle.coreLoop.map((step,index)=><div key={step}><b>{index + 1}</b><span>{step}</span>{index < lord.playstyle.coreLoop.length - 1 && <i>→</i>}</div>)}</div>
        <div className="guide-label"><span>02</span><div><h3>โครงทีมที่ควรมองหา</h3><p>เน้นหน้าที่ของสมาชิก ไม่จำเป็นต้องเป็นเผ่าเดียวกัน</p></div></div><div className="team-blueprint">{lord.playstyle.team.map(([role,amount,reason])=><article key={role}><div><h4>{role}</h4><b>{amount}</b></div><p>{reason}</p></article>)}</div>
        <div className="recommended-monsters"><div className="recommended-heading"><div><small>TEAM OPTIONS</small><h3>มอนสเตอร์แนะนำ</h3></div><span>กดรูปเพื่อเปิดข้อมูล</span></div><div>{lord.playstyle.recommendedMonsters.map(([name,match,reason])=>{ const monster = monsters.find((item)=>item[0] === name); if (!monster) return null; const [,tier,type,,,hasPage] = monster; const prototype = prototypeMonsters.find((item)=>item.name === name); const href = prototype ? `/wiki/monsters/${prototype.slug}` : `https://dungeonwithin.miraheze.org/wiki/${name.replaceAll(' ', '_')}`; return <a href={href} target={prototype ? undefined : '_blank'} rel={prototype ? undefined : 'noreferrer'} key={name}><div className="recommended-image"><img loading="lazy" src={monsterImagePath(name,tier)} alt={`ภาพมอนสเตอร์แนะนำ ${name}`} /><b>Tier {tier}</b></div><div><h4>{name}</h4><small>{type} · {match}</small><p>{reason}</p><span>{prototype ? 'อ่านฉบับไทย →' : hasPage ? 'เปิดต้นทาง ↗' : 'ดูข้อมูลต้นทาง ↗'}</span></div></a>})}</div></div>
        <div className="fit-panel"><h3>ตัวเลือกที่เข้ากับแผน</h3>{lord.playstyle.goodFits.map((fit)=><p key={fit}>✓ <span>{fit}</span></p>)}</div>
        <div className="guide-label"><span>03</span><div><h3>เลือก Authority ตามจังหวะ</h3><p>ชื่อที่ควรมองหาและเหตุผลที่ใช้ในแต่ละช่วง</p></div></div><div className="authority-plan">{lord.playstyle.authorityPlan.map(([timing,names,reason])=><article key={timing}><small>{timing}</small><h4>{names}</h4><p>{reason}</p></article>)}</div>
        <div className="guide-label"><span>04</span><div><h3>แผนต้น–กลาง–ท้าย Run</h3><p>เป้าหมายสำคัญเปลี่ยนไปตามความพร้อมของทีม</p></div></div><div className="run-plan">{lord.playstyle.phases.map(([phase,plan])=><article key={phase}><b>{phase}</b><p>{plan}</p></article>)}</div>
        <div className="pitfall-panel"><h3>ข้อผิดพลาดที่พบบ่อย</h3><ul>{lord.playstyle.pitfalls.map((pitfall)=><li key={pitfall}>{pitfall}</li>)}</ul></div>
        <div className="guide-evidence"><b>ระดับความมั่นใจของคำแนะนำ</b><p>{lord.playstyle.confidence}</p><div><a href={`https://dungeonwithin.miraheze.org/wiki/${lord.name}`} target="_blank" rel="noreferrer">กลไกจาก Wiki ↗</a><a href={communitySource} target="_blank" rel="noreferrer">ตัวอย่างจากชุมชน ↗</a></div></div>
      </section>
      <section><div className="section-title-row"><h2>ค่าสถานะตั้งต้น</h2><span>จาก Wiki อังกฤษ</span></div><div className="stats-grid">{statEntries.map(([name, value]) => <div key={name}><small>{name}</small><b>{value}</b></div>)}</div><p className="inline-warning">ตัวเลขทั้งหมดต้องตรวจซ้ำในเกม เพราะ v0.6.0 ปรับ Ability Score และ Dice Damage</p></section>
      <section><div className="section-title-row"><h2>สกิลและชิ้นส่วน</h2><span>ชื่อไทยพร้อมชื่ออังกฤษ</span></div><div className="skill-list">{lord.skills.map(([slot,english,thai,type,description]) => <article key={english}><b>{slot}</b><div><strong>{thai}</strong><small>{english}</small><p>{description}</p></div><span>{type}</span></article>)}</div></section>
      <section><div className="section-title-row"><h2>อำนาจจอมมาร</h2><span>Authority</span></div><div className="authority-list">{lord.authorities.map(([english,thai,description], index) => <article key={english}><b>{String(index + 1).padStart(2,'0')}</b><div><strong>{thai}</strong><small>{english}</small><p>{description}</p></div></article>)}</div></section>
      <section><h2>Relic ที่เชื่อมกับธีม</h2><div className="relic-grid">{lord.relics.map((item) => <div key={item}>◇<span>{item}</span></div>)}</div></section>
      <section className="missing-section"><h2>ข้อมูลที่ยังขาด</h2><ul><li>Promotion ทุกขั้น</li><li>Ascension Option</li><li>Aspect และระดับ</li><li>สูตร Authority และ Cooldown ปัจจุบัน</li><li>Build ที่ทดสอบกับ v0.6.0</li></ul></section>
    </article><aside className="detail-side"><div><small>แหล่งข้อมูลแก้ไขล่าสุด</small><b>{lord.sourceUpdated}</b></div><div><small>สถานะ</small><b>กลไกตรวจแล้ว · Guide รอทดสอบ</b></div><a className="featured-side-link" href="#playstyle">แนวทางเล่นและจัดทีม ↓</a><a href="/wiki/status-effects">พจนานุกรมสถานะ →</a><a href={`https://dungeonwithin.miraheze.org/wiki/${lord.name}`} target="_blank" rel="noreferrer">เปิด Wiki ต้นทาง ↗</a><a href="/wiki/dark-lords">← กลับหน้าจอมมาร</a></aside></section><SiteFooter />
  </main>;
}
