import SiteHeader, { SiteFooter } from '../../components/site-header';

const stats = [
  { code: 'STR', name: 'พละกำลัง', role: 'ใช้คำนวณ Attack Roll, Damage, DC หรือ Check เมื่อสกิลระบุ STR', note: 'พบบ่อยในสกิลประชิด แต่ไม่ได้แปลว่า Physical เสมอ', tone: 'red' },
  { code: 'DEX', name: 'ความคล่องตัว', role: 'ใช้กับสกิล DEX และช่วยกำหนด Initiative', note: 'ใช้ได้ทั้ง Melee และ Ranged ไม่ได้จำกัดเฉพาะธนู', tone: 'green' },
  { code: 'CON', name: 'ความทรหด', role: 'ใช้ CON Save และสกิลที่ Based on CON; CON ของจอมมารช่วย Max HP', note: 'ไม่ใช่ AC และไม่ได้หมายถึงเกราะโดยตรง', tone: 'gold' },
  { code: 'INT', name: 'สติปัญญา', role: 'ใช้กับ Attack Roll, Damage, DC หรือ Check ของสกิล INT', note: 'พบบ่อยใน Spell แต่ Spell ไม่จำเป็นต้องใช้ INT', tone: 'blue' },
  { code: 'WIS', name: 'ปัญญาญาณ', role: 'ใช้กับสกิล WIS, WIS Save และ Check ตรวจจับบางชนิด', note: 'สร้าง Damage โดยตรงได้ ไม่ใช่ค่าสนับสนุนอย่างเดียว', tone: 'violet' },
  { code: 'CHA', name: 'บารมี / พลังอิทธิพล', role: 'ใช้กับ Damage, DC, Heal หรือเอฟเฟกต์ของสกิล CHA', note: 'ไม่กำหนดชนิด Damage และไม่ได้มีไว้ควบคุมอย่างเดียว', tone: 'rose' },
];

const modifiers = [['6–7','−2'],['8–9','−1'],['10–11','+0'],['12–13','+1'],['14–15','+2'],['16–17','+3'],['18–19','+4'],['20–21','+5']];

export default function StatsPage() {
  return <main className="hub-page"><SiteHeader />
    <section className="data-hero stats-hero"><p className="breadcrumbs"><a href="/wiki">คลังข้อมูล</a><span>/</span>ค่าสถานะ</p><p className="eyebrow"><span /> Combat fundamentals</p><h1>STR, DEX, CON,<br />INT, WIS, CHA คืออะไร?</h1><p>คู่มืออ่านค่าสถานะ Key Stat และข้อความบนสกิล โดยแยกออกจากระยะโจมตี แท็ก Spell และชนิดความเสียหาย</p></section>
    <section className="hub-content stats-content">
      <div className="stat-answer"><span>คำตอบสั้นที่สุด</span><h2>Stat ไม่ได้บอกว่าเป็น<br /><em>กายภาพหรือเวทมนตร์</em></h2><p>ค่าสถานะบอกว่าเกมนำ Modifier ตัวไหนไปคำนวณ ส่วนลักษณะการโจมตีให้อ่านจาก <b>Melee / Ranged / Spell</b> และชนิดความเสียหาย เช่น Slashing, Fire หรือ Psychic</p></div>

      <section><div className="section-title-row"><h2>ค่าสถานะหลักทั้ง 6</h2><span>Core Stats</span></div><div className="stat-card-grid">{stats.map((stat)=><article className={stat.tone} key={stat.code}><div><b>{stat.code}</b><span>{stat.name}</span></div><p>{stat.role}</p><small>{stat.note}</small></article>)}</div></section>

      <section className="reading-layers"><div className="section-title-row"><h2>อ่านสกิลแยกเป็น 3 ชั้น</h2><span>อย่ารวมเป็นเรื่องเดียวกัน</span></div><div><article><b>01</b><span><strong>Based on [STAT]</strong><small>ใช้ Modifier ของค่าใดคำนวณ</small></span></article><i>→</i><article><b>02</b><span><strong>Melee / Ranged / Spell</strong><small>ระยะและแท็กของความสามารถ</small></span></article><i>→</i><article><b>03</b><span><strong>Damage Type</strong><small>ชนิดที่ใช้ตรวจต้านทานและแพ้ทาง</small></span></article></div></section>

      <section className="key-stat-panel"><div><p className="eyebrow"><span /> เครื่องหมาย *</p><h2>Key Stat ไม่ใช่ค่าสถานะลำดับที่เจ็ด</h2><p>มันคือหนึ่งใน STR–CHA ที่เป็นแกนหลักของยูนิต โดยทั่วไปเป็นค่าสูงสุดและเป็นค่าที่การโจมตีส่วนใหญ่ใช้ หากทอย Save หรือ Check ด้วย Key Stat จะได้รับ Proficiency Bonus เพิ่มตาม Tier</p></div><div className="key-stat-example"><small>ตัวอย่าง</small><strong>DEX 18*</strong><span>Ability Modifier <b>+4</b></span><span>Tier 5 PB <b>+4</b></span><em>DEX Attack Roll = 1d20 + 4 + 4</em></div></section>

      <section className="dice-guide"><div className="section-title-row"><h2>เริ่มจากภาษาลูกเต๋า: 2d6 อ่านอย่างไร?</h2><span>Dice notation</span></div><p className="section-intro">รูปแบบทั่วไปคือ <b>XdY</b> โดย X บอกจำนวนลูกเต๋า และ Y บอกจำนวนหน้าของลูกเต๋า เกมจะสุ่มผลของแต่ละลูกแล้วนำมารวมกัน</p><div className="dice-expression" aria-label="แยกความหมายสูตร 2d6 บวก DEX Modifier"><div><strong>2</strong><span>จำนวนลูกเต๋า</span><small>ทอยทั้งหมด 2 ลูก</small></div><i>×</i><div><strong>d</strong><span>ย่อจาก Dice</span><small>เครื่องหมายการทอยเต๋า</small></div><i>×</i><div><strong>6</strong><span>จำนวนหน้า</span><small>แต่ละลูกออกได้ 1–6</small></div><i>+</i><div><strong>DEX</strong><span>ค่า Modifier</span><small>ใช้ค่าที่แปลงแล้ว ไม่ใช่ DEX ดิบ</small></div></div><div className="worked-example"><div><small>ตัวอย่างการทอย</small><code>2d6 + DEX Modifier</code></div><ol><li><span>ลูกที่ 1</span><b>ออก 4</b></li><li><span>ลูกที่ 2</span><b>ออก 5</b></li><li><span>DEX 17</span><b>Modifier +3</b></li><li className="total"><span>รวมความเสียหาย</span><b>4 + 5 + 3 = 12</b></li></ol></div><div className="dice-notes"><p><b>ช่วงของ 2d6</b><span>ต่ำสุด 2 สูงสุด 12 และค่าเฉลี่ย 7 ก่อนบวก Modifier</span></p><p><b>3d8 หมายถึง</b><span>ทอย d8 จำนวน 3 ลูก ผลรวมอยู่ระหว่าง 3–24</span></p><p><b>เครื่องหมาย +3</b><span>เป็นค่าคงที่ จึงบวกหลังรวมหน้าลูกเต๋าแล้ว</span></p></div></section>

      <section className="formula-section"><div><div className="section-title-row"><h2>Ability Modifier</h2><span>ค่าที่ใช้จริงในการต่อสู้</span></div><p>เกมไม่ได้หยิบตัวเลข Stat ไปบวกตรง ๆ แต่แปลงด้วยสูตรนี้ก่อน</p><code>floor((STAT − 10) ÷ 2)</code><div className="modifier-grid">{modifiers.map(([score,modifier])=><div key={score}><small>STAT {score}</small><b>{modifier}</b></div>)}</div></div><aside><small>ตัวอย่างสกิล</small><h3>2d6 + DEX<br /><span>Slashing Damage</span></h3><p>ถ้า DEX = 17 จะได้ Modifier +3 ดังนั้น Damage พื้นฐานคือ <b>2d6 + 3</b> ก่อนคิดตัวปรับอื่น</p></aside></section>

      <section className="roll-explainer"><div className="section-title-row"><h2>1d20 + Modifier + PB แยกทีละคำ</h2><span>ใช้ตรวจว่าโจมตีโดนหรือไม่</span></div><div className="roll-term-grid"><article><code>1d20</code><b>ทอยลูกเต๋า 20 หน้า 1 ลูก</b><p>ผลสุ่มตั้งแต่ 1 ถึง 20 เป็นฐานของการตรวจสอบครั้งนี้</p></article><article><code>Modifier</code><b>ตัวปรับจากค่าสถานะ</b><p>ถ้าใช้ DEX 18 จะนำ Ability Modifier <strong>+4</strong> มาบวก ไม่ได้นำเลข 18 มาบวก</p></article><article><code>PB</code><b>Proficiency Bonus</b><p>โบนัสความชำนาญตาม Tier บวกเมื่อกฎระบุว่ายูนิตชำนาญในการทอยนั้น</p></article><article><code>AC / DC</code><b>เลขเป้าหมายที่ต้องเอาชนะ</b><p>Attack Roll เทียบกับ AC ส่วน Saving Throw เทียบกับ DC ผลรวมเท่ากับหรือสูงกว่าจึงสำเร็จ</p></article></div><div className="roll-flow"><span><small>หน้าลูกเต๋า</small><b>11</b></span><i>+</i><span><small>DEX Modifier</small><b>4</b></span><i>+</i><span><small>PB</small><b>4</b></span><i>=</i><span className="roll-total"><small>Attack Roll</small><b>19</b></span><i>เทียบกับ</i><span><small>เป้าหมาย</small><b>AC 17</b></span></div><p className="roll-result"><b>19 ≥ 17 จึงโจมตีโดน</b> — จากนั้นจึงทอยสูตร Damage ของสกิลแยกอีกครั้ง เช่น <code>2d6 + 4</code></p></section>

      <section className="roll-comparison"><div><small>ขั้นที่ 1 · ฝ่ายโจมตี</small><h2>Attack Roll</h2><code>1d20 + Ability Modifier + PB</code><p><b>ตอบคำถามว่า “โดนไหม?”</b> นำผลรวมไปเทียบกับ AC เป้าหมาย หากไม่ถึง AC การโจมตีพลาดและปกติจะไม่ทอย Damage</p></div><div><small>เมื่อถูกเอฟเฟกต์บังคับ</small><h2>Saving Throw</h2><code>1d20 + Ability Modifier (+ PB เมื่อเข้าเงื่อนไข)</code><p><b>ตอบคำถามว่า “ต้านผลได้ไหม?”</b> ฝ่ายรับเป็นผู้ทอยแล้วเทียบกับ DC หาก Stat ที่ใช้ Save เป็น Key Stat ของฝ่ายรับจึงบวก PB เพิ่ม</p></div><div className="damage-roll-card"><small>ขั้นที่ 2 · เมื่อโจมตีโดน</small><h2>Damage Roll</h2><code>จำนวนลูกเต๋า + Ability Modifier</code><p><b>ตอบคำถามว่า “เสียหายเท่าไร?”</b> เช่น <code>2d6 + DEX</code> ไม่ได้นำไปเทียบ AC แต่ใช้หาจำนวน Damage ก่อนตรวจ Resistance, Immunity หรือ Vulnerability</p></div></section>

      <section className="skill-reading"><div className="section-title-row"><h2>ตัวอย่างการอ่านหนึ่งสกิล</h2><span>แยกทุกคำออกจากกัน</span></div><div className="skill-sample"><code>3d8 + INT Necrotic Damage</code><p>Based on INT · Ranged · Spell · INT Attack Roll</p></div><ul><li><b>3d8</b> ทอยลูกเต๋า 8 หน้า 3 ลูก แล้วรวมกัน (3–24)</li><li><b>+ INT</b> บวก INT Modifier ไม่ใช่คะแนน INT ดิบ</li><li><b>INT Attack Roll</b> ใช้ INT Modifier ในการทอยให้โดน</li><li><b>Ranged</b> โจมตีแนวหลังได้ตามกฎเป้าหมาย</li><li><b>Spell</b> ทำให้โต้ตอบกับเอฟเฟกต์ที่ระบุ Spell</li><li><b>Necrotic</b> คือชนิด Damage ที่ใช้ตรวจ Resistance/Immunity/Vulnerability</li></ul><div className="reading-order"><b>ลำดับตอนใช้จริง</b><span>① ทอย Attack Roll → ② เทียบ AC → ③ ถ้าโดน ทอย 3d8 และบวก INT Modifier → ④ ตรวจการต้านทาน Necrotic</span></div></section>

      <div className="inline-warning">ข้อมูลสูตรอิงหน้า Stats และ Combat ของ Wiki ชุมชนซึ่งถอดความจาก Guidebook ในเกม ตัวเลขที่อาจเปลี่ยนตาม Patch จะต้องตรวจซ้ำกับ v0.6.0</div>
    </section><SiteFooter />
  </main>;
}
